app/controllers/application_controller.rb
app/controllers/pages_controller.rb
db/seeds.rb

Can you validate that setup of devise is ok?
tx

finalized devise install

---

db/migrate/20180313115057_add_fields_to_products.rb
db/schema.rb
db/seeds.rb

Added description and location fields to Product model for Emile!

added description and location to products

---

app/controllers/products_controller.rb
app/views/products/new.html.erb

Hey just finished the new page and need some validation. After that we have to redirect to the show and not the index .

Products new create

---

app/views/pages/home.html.erb

Clearing my git status. Do not impletement those changes

clearing home

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_container.scss
app/views/products/index.html.erb
db/seeds.rb

Changed the card styling and added a title

modified index

---

app/controllers/application_controller.rb
app/views/devise/registrations/new.html.erb

Add code in the application controller in order to allow the import of the GitHub username into the User table (field: username)

corrected the avatar feature

---

app/views/shared/_navbar.html.erb

added link to navbar menu to redirect user towards product new

added link to navbar menu to redirect user towards product new

---

db/seeds.rb

Micro changement dans le seed pour eviter des erreurs liées à des duplicate entries (cf les product 4, 5, 6 qui étaient identiques)

changed seed to avoid duplicate entries

---

Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/models/product.rb
app/uploaders/photo_uploader.rb
app/views/products/new.html.erb
db/migrate/20180313160305_add_photo_to_products.rb
db/schema.rb

Update new product

---

app/assets/stylesheets/components/_booking.scss
app/assets/stylesheets/components/_index.scss
app/controllers/bookings_controller.rb
app/controllers/products_controller.rb
app/controllers/users_controller.rb
app/views/products/index.html.erb
app/views/products/show.html.erb
app/views/shared/_navbar.html.erb
app/views/users/dashboard.html.erb
config/routes.rb
db/seeds.rb
yarn-error.log

> Finalized bookings controller's create action
> Prepared dashboard v1

finalized create controller and prepared dashboard v1

---

app/assets/stylesheets/components/_container-show.scss
app/assets/stylesheets/components/_index.scss
app/controllers/bookings_controller.rb
app/views/products/show.html.erb
db/migrate/20180313173058_change_message_column_in_bookings.rb
db/schema.rb

could you accept my pool request?

Controller booking v2

---

app/views/products/index.html.erb
yarn-error.log

replaced location by index on the index

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/products/show.html.erb

A couple cosmectics clean ups:
> Pages home: responsiveness improved
> Show: incorrect image_tag corrected + commented back button which sends user back to unfiltered index

better home responsivness

---

app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_new.scss
app/views/products/new.html.erb
app/views/products/show.html.erb

Hello guys, 
check the New page --> the form is updated. I reused the work done on the banner.

updated new form

---

app/views/shared/_navbar.html.erb

cleanup dashbopard

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/shared/_navbar.html.erb
app/views/users/dashboard.html.erb

reinstated links to change status

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_searchbar.scss
app/assets/stylesheets/config/_fonts.scss
app/controllers/products_controller.rb
app/views/pages/home.html.erb
app/views/products/index.html.erb
config/initializers/kaminari_config.rb
db/seeds.rb

Added pages turner // limited to 6 results per page on index

kaminari gem

---

app/assets/stylesheets/components/_booking.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_tabs.scss
app/models/booking.rb
app/views/users/dashboard.html.erb

upload owner dash

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

last version

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/pages/home.html.erb

cosmetics changes

---

app/assets/stylesheets/components/_tabs.scss
app/views/users/dashboard.html.erb

Hello guys, 
final version !!!!!

Improving dashboard
